### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by vseguin** [GLO3102/UFood#2]
- [x] GET restaurants / GET restaurants/:id
- [x] Add genres, price_range, q and limit filters to restaurants
- [x] Add geo filters (bbox) to restaurants
- [x] GET /favorites, GET /favorites/:id
- [x] POST /favorites
- [x] PUT /favorites/:id
- [x] DELETE /favorites/:id
- [x] POST /favorites/:id/restaurants
- [x] DELETE /favorites/:id/restaurants/:restaurantId
- [x] Add `search` to users
- [x] Add `followers` to users
- [x] GET /users/:id/favorites
- [x] GET /users/:id/restaurants/visits, GET /users/:id/restaurants/visits/:visitId
- [x] POST /users/:id/restaurants/visits

Note
- Creating a visit should increase the user **rating**
- Creating a visit should change the restaurant **rating**
